name: Desplegar a Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Desplegar a Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" --non-interactive --project gastosmarcioyangie
        env:
          CI: true
